name: "Windows Unsigned Build"

on:
  workflow_dispatch:

jobs:
  build-windows:
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      platform: "windows-latest"
      target: "x86_64-pc-windows-msvc"
      build-args: ""
      sign-binaries: false
      disable-windows-sign-command: true
      disable-updater-signing: true
      upload-artifacts: true
      asset-prefix: "handy-unsigned"
    secrets: inherit
